import cod from "../assets/imgs/cod.png";
import clownFish from "../assets/imgs/clown-fish.png";
import trout from "../assets/imgs/trout.png";
import sableFish from "../assets/imgs/sablefish.png";

const SpeciesObjects = () => {
  const speciesObjects = [
    {
      name: "Cod Fish",
      subname: "fish",
      endangered: "Endangered",
      lifeExp: "up to 25 years",
      weight: "2.4 kg",
      length: "26 cm",
      info: "Tasty Fish",
      img: cod,
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Clown Fish",
      subname: "fish",
      endangered: "Endangered",
      lifeExp: "up to 2 years",
      info: "Tasty Fish",
      img: clownFish,
      length: "26 cm",
      weight: "4.41 kg",
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Sable Fish",
      subname: "fish",
      endangered: "Endangered",
      lifeExp: "up to 5 years",
      info: "Tasty Fish",
      img: trout,
      weight: "22.4 kg",
      length: "26 cm",
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Trout Fish",
      subname: "fish",
      endangered: "Endangered",
      lifeExp: "up to 35 years",
      info: "Tasty Fish",
      img: sableFish,
      weight: "4.3 kg",
      length: "26 cm",
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Cod Fish",
      subname: "fish",
      endangered: "Endangered",
      length: "26 cm",
      lifeExp: "up to 25 years",
      weight: "2.4 kg",
      info: "Tasty Fish",
      img: cod,
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Clown Fish",
      subname: "fish",
      endangered: "Endangered",
      length: "26 cm",
      lifeExp: "up to 2 years",
      info: "Tasty Fish",
      img: clownFish,
      weight: "4.41 kg",
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Sable Fish",
      subname: "fish",
      length: "26 cm",
      endangered: "Endangered",
      lifeExp: "up to 5 years",
      info: "Tasty Fish",
      img: trout,
      weight: "22.4 kg",
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Trout Fish",
      length: "26 cm",
      subname: "fish",
      endangered: "Endangered",
      lifeExp: "up to 35 years",
      info: "Tasty Fish",
      img: sableFish,
      weight: "4.3 kg",
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Cod Fish",
      length: "26 cm",
      subname: "fish",
      endangered: "Endangered",
      lifeExp: "up to 25 years",
      weight: "2.4 kg",
      info: "Tasty Fish",
      img: cod,
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Clown Fish",
      length: "26 cm",
      subname: "fish",
      endangered: "Endangered",
      lifeExp: "up to 2 years",
      info: "Tasty Fish",
      img: clownFish,
      weight: "4.41 kg",
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
    {
      name: "Sable Fish",
      subname: "fish",
      length: "26 cm",
      endangered: "Endangered",
      lifeExp: "up to 5 years",
      info: "Tasty Fish",
      img: trout,
      weight: "22.4 kg",
      desc: "The Atlantic Cod has a generally spotted body, a leaden-silvery peritoneum with black dots, small eyes, a stout caudal peduncle, and a lateral line that is paler in colour than the adjacent areas of the body.",
      fact: "The Laurentian North population of Atlantic Cod has declined between 76% and 89% over the last three generations (about 30 years).",
    },
  ];
  return speciesObjects;
};

export default SpeciesObjects;
